[package]
name = "rust_lib_nofi2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
clap = { version = "4.5.16", features = ["derive", "string"] }
flutter_rust_bridge = "=2.3.0"
image = "0.25.2"
indicium = "0.6.2"
